"""Signed and encrypted approved team-state restoration."""

from intent_engineering.team_state.archive import (
    RestoredSnapshot,
    build_archive,
    validate_archive,
)
from intent_engineering.team_state.crypto import (
    EncryptedBundle,
    decrypt_bundle,
    encrypt_bundle,
)
from intent_engineering.team_state.git_ref import GitRefReader
from intent_engineering.team_state.keys import (
    GitHubIdentity,
    GitHubIdentityVerifier,
    InMemoryRecipientKeyStore,
    KeyringRecipientKeyStore,
    RecipientEnrollmentBinding,
    RecipientKeyStore,
    RecipientKeyStoreError,
)
from intent_engineering.team_state.models import (
    BundleInventory,
    BundleInventoryEntry,
    CanonicalStateFile,
    CanonicalStateSnapshot,
    PreparedPublication,
    PublicationLineage,
    RecipientRecord,
    RemoteStateSnapshot,
    TeamStateManifest,
    canonical_manifest_bytes,
)
from intent_engineering.team_state.restore import (
    CANONICAL_STATE_PATHS,
    EnvironmentTrustProvider,
    GitSharedStateRestorer,
    RecipientKeyStoreTrustProvider,
    SharedStateArtifacts,
    SharedStateTrust,
    StaticTrustProvider,
    TeamStateRestorer,
    TrustedSigningKey,
    build_state_payload,
    seal_state_payload,
)

__all__ = [
    "CANONICAL_STATE_PATHS",
    "BundleInventory",
    "BundleInventoryEntry",
    "CanonicalStateFile",
    "CanonicalStateSnapshot",
    "EncryptedBundle",
    "EnvironmentTrustProvider",
    "GitHubIdentity",
    "GitHubIdentityVerifier",
    "GitRefReader",
    "GitSharedStateRestorer",
    "InMemoryRecipientKeyStore",
    "KeyringRecipientKeyStore",
    "PreparedPublication",
    "PublicationLineage",
    "RecipientEnrollmentBinding",
    "RecipientKeyStore",
    "RecipientKeyStoreError",
    "RecipientKeyStoreTrustProvider",
    "RecipientRecord",
    "RemoteStateSnapshot",
    "RestoredSnapshot",
    "SharedStateArtifacts",
    "SharedStateTrust",
    "StaticTrustProvider",
    "TeamStateManifest",
    "TeamStateRestorer",
    "TrustedSigningKey",
    "build_archive",
    "build_state_payload",
    "canonical_manifest_bytes",
    "decrypt_bundle",
    "encrypt_bundle",
    "seal_state_payload",
    "validate_archive",
]
