"""Signed and encrypted approved team-state restoration."""

from intent_engineering.team_state.archive import (
    ARCHIVE_V2_MAGIC,
    AUTHORITY_PATH,
    RestoredSnapshot,
    build_archive,
    build_archive_v2,
    validate_archive,
    validate_archive_v2,
    validate_versioned_archive,
)
from intent_engineering.team_state.crypto import (
    EncryptedBundle,
    decrypt_bundle,
    encrypt_bundle,
)
from intent_engineering.team_state.git_ref import GitRefReader
from intent_engineering.team_state.keys import (
    GitHubIdentity,
    GitHubIdentityVerifier,
    InMemoryRecipientKeyStore,
    KeyringRecipientKeyStore,
    RecipientEnrollmentBinding,
    RecipientKeyStore,
    RecipientKeyStoreError,
)
from intent_engineering.team_state.models import (
    BundleInventory,
    BundleInventoryEntry,
    CanonicalStateFile,
    CanonicalStateSnapshot,
    PreparedPublication,
    PublicationLineage,
    RecipientRecord,
    RemoteStateSnapshot,
    RestoredSnapshotV2,
    TeamStateManifest,
    canonical_manifest_bytes,
)
from intent_engineering.team_state.publication import (
    PublicationAuthority,
    PublicationCleanupError,
    PublicationPreview,
    PublicationPublisher,
    PublicationService,
    TemporaryWorktreePublisher,
)
from intent_engineering.team_state.restore import (
    CANONICAL_STATE_PATHS,
    EnvironmentTrustProvider,
    GitSharedStateRestorer,
    RecipientKeyStoreTrustProvider,
    SharedStateArtifacts,
    SharedStateTrust,
    StaticTrustProvider,
    TeamStateRestorer,
    TeamStateRestoreRuntime,
    TrustedSigningKey,
    build_state_payload,
    seal_state_payload,
)

__all__ = [
    "ARCHIVE_V2_MAGIC",
    "AUTHORITY_PATH",
    "CANONICAL_STATE_PATHS",
    "BundleInventory",
    "BundleInventoryEntry",
    "CanonicalStateFile",
    "CanonicalStateSnapshot",
    "EncryptedBundle",
    "EnvironmentTrustProvider",
    "GitHubIdentity",
    "GitHubIdentityVerifier",
    "GitRefReader",
    "GitSharedStateRestorer",
    "InMemoryRecipientKeyStore",
    "KeyringRecipientKeyStore",
    "PreparedPublication",
    "PublicationAuthority",
    "PublicationCleanupError",
    "PublicationLineage",
    "PublicationPreview",
    "PublicationPublisher",
    "PublicationService",
    "RecipientEnrollmentBinding",
    "RecipientKeyStore",
    "RecipientKeyStoreError",
    "RecipientKeyStoreTrustProvider",
    "RecipientRecord",
    "RemoteStateSnapshot",
    "RestoredSnapshot",
    "RestoredSnapshotV2",
    "SharedStateArtifacts",
    "SharedStateTrust",
    "StaticTrustProvider",
    "TeamStateManifest",
    "TeamStateRestoreRuntime",
    "TeamStateRestorer",
    "TemporaryWorktreePublisher",
    "TrustedSigningKey",
    "build_archive",
    "build_archive_v2",
    "build_state_payload",
    "canonical_manifest_bytes",
    "decrypt_bundle",
    "encrypt_bundle",
    "seal_state_payload",
    "validate_archive",
    "validate_archive_v2",
    "validate_versioned_archive",
]
